### ISSUE TITLE
Aws Account ID 및 내부 IP 유출하지 않도록 조심해주세요!!

### ISSUE THREAD

**Issue by coodns** [Junho-06/CI-CD#1]
AWS ACCOUNT ID 및 내부 IP가 Jenkinsfile 에 노출되어있는것 같은데 Account ID 및 내부IP 는 외부적으론 문제가 없지만 혹여나 다른 보안사항이 노출 되었을시 공격의 힌트가 될 수 있습니다.

주의 하면 좋을것 같습니다..!

추가적으로 젠킨스 파일에 파라미터  값을 선언하신것 같은데 해당 방법 보단 파일로 정리 후 해당 파일을 젠킨스에서 같이 불러오는 방식으로 하는것이 보안적으로 안전해 보입니다. 한번 적용해보시죠!

best regards @Junho-06

**Comment by Junho-06** [comment]
수정하였습니다!
